---
title: "Flexible Bayesian estimation of incubation times"
output: github_document
author: Oswaldo Gressani
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Reproducibility instructions

This repository contains all the routines required to reproduce the results in the paper entitled “Flexible Bayesian estimation on incubation times”. It has two main folders (**01-Simulations** and **02-RealData**). 

- **01-Simulations** contains simulation results of the main manuscript as well as additional results for validating the model.

- **02-RealData** contains results related to real data applications.

### Simulation environment

Simulations and applications to real data were implemented in the following environment:

- Windows 11 Pro (64-bit OS) with Intel Xeon W-2255 CPU @3.70GHz and 32GB of RAM.
- R version 4.3.3 (2024-02-29 ucrt) -- "Angel Food Cake" x86_64-w64-mingw32/x64 (64-bit).
- EpiLPS package version 1.3.0 [https://cran.r-project.org/package=EpiLPS](https://cran.r-project.org/package=EpiLPS). 
- See SessionInfo.txt file to see a detailed session information provided by utils::sessionInfo().

Readers and users are encouraged to reproduce the results contained in this folder. 

### Website
[https://epilps.com/](https://epilps.com/)

### Repository version
This is version 0.3.0 (2024-05-14) - “IncubLPS-V4”.

### License
Copyright © Oswaldo Gressani. All rights reserved.
